Add resource application with exponential retries

diff --git a/gordo_components/workflow/workflow_generator/resources/argo-workflow.yml.template b/gordo_components/workflow/workflow_generator/resources/argo-workflow.yml.template
--- a/gordo_components/workflow/workflow_generator/resources/argo-workflow.yml.template
+++ b/gordo_components/workflow/workflow_generator/resources/argo-workflow.yml.template
@@ -80,120 +80,194 @@ spec:
       - name: GORDO_PROJECT_VERSION
         value: "{{project_version}}"
 
+  - name: apply-with-retries
+    retryStrategy:
+      limit: 4
+    inputs:
+      parameters:
+        - name: resource
+    metadata:
+      labels:
+        app: apply-with-retries
+        applications.gordo.equinor.com/project-name: "{{project_name}}"
+        applications.gordo.equinor.com/project-version: "{{project_version}}"
+    script:
+      image: {{ docker_registry }}/{{ docker_repository }}/gordo-deploy:{{gordo_version}}
+      command: [bash]
+      source: |
+        # Retries a command a configurable number of times with backoff.
+        #
+        # The retry count is given by ATTEMPTS (default 5), the initial backoff
+        # timeout is given by TIMEOUT in seconds (default 15.)
+        #
+        # Successive backoffs double the timeout.
+        # Thanks to  `phs` from stackoverflow:
+        # https://stackoverflow.com/questions/8350942/how-to-re-run-the-curl-command-automatically-when-the-error-occurs/8351489#8351489
+        function with_backoff {
+            local max_attempts=${ATTEMPTS-5}
+            local timeout=${TIMEOUT-15}
+            local attempt=1
+            local exitCode=0
+
+            while (( $attempt < $max_attempts ))
+            do
+                if "$@"
+                then
+                    return 0
+                else
+                    exitCode=$?
+                fi
+                echo "Got exitcode $exitCode" 1>&2
+                echo "Failure! Retrying in $timeout.." 1>&2
+                sleep $timeout
+                attempt=$(( attempt + 1 ))
+                timeout=$(( timeout * 2 ))
+            done
+
+            if [[ $exitCode != 0 ]]
+            then
+                echo "Command failed too many times, exiting! ($@)" 1>&2
+            fi
+
+            return $exitCode
+        }
+
+        function apply_once {
+            echo "$K_RESOURCE" | kubectl apply -f -
+        }
+        echo "applying resource:" 1>&2
+        echo "$K_RESOURCE" 1>&2
+        with_backoff apply_once
+
+
+      resources:
+        requests:
+          memory: "100M"
+          cpu: "2m"
+        limits:
+          memory: "200M"
+          cpu: "100m"
+      env:
+      - name: K_RESOURCE
+        value: {{ '"{{inputs.parameters.resource}}" '}}
 
   - name: gordo-influx-service
-    retryStrategy:
-      limit: 5
-    resource:
-      action: apply
-      manifest: |
-        apiVersion: v1
-        kind: Service
-        metadata:
-          name: gordo-influx-{{project_name}}
-          labels:
-            app: gordo-influx-{{project_name}}
-            app.kubernetes.io/name: influx
-            app.kubernetes.io/component: service
-            app.kubernetes.io/part-of: gordo
-            app.kubernetes.io/managed-by: gordo
-            applications.gordo.equinor.com/project-name: "{{project_name}}"
-            applications.gordo.equinor.com/project-version: "{{project_version}}"
-         {% if owner_references is defined %}
-          ownerReferences: {{owner_references}}
-        {% endif %}
-        spec:
-          selector:
-            app: gordo-influx-{{project_name}}
-          ports:
-          - port: 8086
-            name: api
-            targetPort: 8086
+    steps:
+      - - name: apply-with-retries
+          template: apply-with-retries
+          arguments:
+            parameters:
+              - name: resource
+                value: |
+                  apiVersion: v1
+                  kind: Service
+                  metadata:
+                    name: gordo-influx-{{project_name}}
+                    labels:
+                      app: gordo-influx-{{project_name}}
+                      app.kubernetes.io/name: influx
+                      app.kubernetes.io/component: service
+                      app.kubernetes.io/part-of: gordo
+                      app.kubernetes.io/managed-by: gordo
+                      applications.gordo.equinor.com/project-name: "{{project_name}}"
+                      applications.gordo.equinor.com/project-version: "{{project_version}}"
+                   {% if owner_references is defined %}
+                    ownerReferences: {{owner_references}}
+                  {% endif %}
+                  spec:
+                    selector:
+                      app: gordo-influx-{{project_name}}
+                    ports:
+                    - port: 8086
+                      name: api
+                      targetPort: 8086
+
   - name: gordo-influx-statefulset
-    retryStrategy:
-      limit: 5
-    resource:
-      action: apply
-      successCondition: status.readyReplicas > 0
-      manifest: |
-        apiVersion: apps/v1
-        kind: StatefulSet
-        metadata:
-          name: gordo-influx-{{project_name}}
-          labels:
-            app: gordo-influx-{{project_name}}
-            app.kubernetes.io/name: influxd-deployment
-            app.kubernetes.io/component: influxdb
-            app.kubernetes.io/part-of: gordo
-            app.kubernetes.io/managed-by: gordo
-            applications.gordo.equinor.com/project-name: "{{project_name}}"
-            applications.gordo.equinor.com/project-version: "{{project_version}}"
-        {% if owner_references is defined %}
-          ownerReferences: {{owner_references}}
-        {% endif %}
-        spec:
-          serviceName: gordo-influx-{{project_name}}
-          volumeClaimTemplates:
-            - metadata:
-                name: influx-storage-{{project_version}}
-                labels:
-                  applications.gordo.equinor.com/project-name: "{{project_name}}"
-                  applications.gordo.equinor.com/project-version: "{{project_version}}"
-                  app.kubernetes.io/part-of: gordo
-                  app.kubernetes.io/managed-by: gordo
-                annotations:
-                  applications.gordo.equinor.com/project-name: "{{project_name}}"
-                  applications.gordo.equinor.com/project-version: "{{project_version}}"
-                {% if owner_references is defined %}
-                ownerReferences: {{owner_references}}
-                {% endif %}
-              spec:
-                accessModes: [ "ReadWriteOnce" ]
-                storageClassName: "managed-premium"
-                resources:
-                  requests:
-                    storage: 28Gi
-          selector:
-            matchLabels:
-              app: gordo-influx-{{project_name}}
-          replicas: 1
-          template:
-            metadata:
-              labels:
-                app: gordo-influx-{{project_name}}
-              {% if owner_references is defined %}
-              ownerReferences: {{owner_references}}
-              {% endif %}
-            spec:
-              containers:
-              - image: "influxdb:1.7.6-alpine"
-                imagePullPolicy: "IfNotPresent"
-                name: gordo-influx-{{project_name}}
-                volumeMounts:
-                  - name: influx-storage-{{project_version}}
-                    mountPath: /var/lib/influxdb
-                ports:
-                  - name: api
-                    containerPort: 8086
-                resources:
-                  requests:
-                    memory: "{{ influx_resources_requests_memory }}M"
-                    cpu: "{{ influx_resources_requests_cpu }}m"
-                  limits:
-                    memory: "{{ influx_resources_limits_memory }}M"
-                    cpu: "{{ influx_resources_limits_cpu }}m"
-                livenessProbe:
-                  httpGet:
-                    path: /ping
-                    port: api
-                  initialDelaySeconds: 30
-                  timeoutSeconds: 5
-                readinessProbe:
-                  httpGet:
-                    path: /ping
-                    port: api
-                  initialDelaySeconds: 5
-                  timeoutSeconds: 1
+    steps:
+      - - name: apply-with-retries
+          template: apply-with-retries
+          arguments:
+            parameters:
+              - name: resource
+                value: |
+                  apiVersion: apps/v1
+                  kind: StatefulSet
+                  metadata:
+                    name: gordo-influx-{{project_name}}
+                    labels:
+                      app: gordo-influx-{{project_name}}
+                      app.kubernetes.io/name: influxd-deployment
+                      app.kubernetes.io/component: influxdb
+                      app.kubernetes.io/part-of: gordo
+                      app.kubernetes.io/managed-by: gordo
+                      applications.gordo.equinor.com/project-name: "{{project_name}}"
+                      applications.gordo.equinor.com/project-version: "{{project_version}}"
+                  {% if owner_references is defined %}
+                    ownerReferences: {{owner_references}}
+                  {% endif %}
+                  spec:
+                    serviceName: gordo-influx-{{project_name}}
+                    volumeClaimTemplates:
+                      - metadata:
+                          name: influx-storage-{{project_version}}
+                          labels:
+                            applications.gordo.equinor.com/project-name: "{{project_name}}"
+                            applications.gordo.equinor.com/project-version: "{{project_version}}"
+                            app.kubernetes.io/part-of: gordo
+                            app.kubernetes.io/managed-by: gordo
+                          annotations:
+                            applications.gordo.equinor.com/project-name: "{{project_name}}"
+                            applications.gordo.equinor.com/project-version: "{{project_version}}"
+                          {% if owner_references is defined %}
+                          ownerReferences: {{owner_references}}
+                          {% endif %}
+                        spec:
+                          accessModes: [ "ReadWriteOnce" ]
+                          storageClassName: "managed-premium"
+                          resources:
+                            requests:
+                              storage: 28Gi
+                    selector:
+                      matchLabels:
+                        app: gordo-influx-{{project_name}}
+                    replicas: 1
+                    template:
+                      metadata:
+                        labels:
+                          app: gordo-influx-{{project_name}}
+                        {% if owner_references is defined %}
+                        ownerReferences: {{owner_references}}
+                        {% endif %}
+                      spec:
+                        containers:
+                        - image: "influxdb:1.7.6-alpine"
+                          imagePullPolicy: "IfNotPresent"
+                          name: gordo-influx-{{project_name}}
+                          volumeMounts:
+                            - name: influx-storage-{{project_version}}
+                              mountPath: /var/lib/influxdb
+                          ports:
+                            - name: api
+                              containerPort: 8086
+                          resources:
+                            requests:
+                              memory: "{{ influx_resources_requests_memory }}M"
+                              cpu: "{{ influx_resources_requests_cpu }}m"
+                            limits:
+                              memory: "{{ influx_resources_limits_memory }}M"
+                              cpu: "{{ influx_resources_limits_cpu }}m"
+                          livenessProbe:
+                            httpGet:
+                              path: /ping
+                              port: api
+                            initialDelaySeconds: 30
+                            timeoutSeconds: 5
+                          readinessProbe:
+                            httpGet:
+                              path: /ping
+                              port: api
+                            initialDelaySeconds: 5
+                            timeoutSeconds: 1
 
   - name: gordo-influx-database-creator
     retryStrategy:
@@ -223,34 +297,36 @@ spec:
         template: gordo-influx-database-creator
 
   - name: gordo-grafana-service
-    retryStrategy:
-      limit: 5
-    resource:
-      action: apply
-      manifest: |
-        ---
-        apiVersion: v1
-        kind: Service
-        metadata:
-          name: gordo-grafana-{{project_name}}
-          labels:
-            app: gordo-grafana-{{project_name}}
-            app.kubernetes.io/name: grafana
-            app.kubernetes.io/component: service
-            app.kubernetes.io/part-of: gordo
-            app.kubernetes.io/managed-by: gordo
-            applications.gordo.equinor.com/project-name: "{{project_name}}"
-            applications.gordo.equinor.com/project-version: "{{project_version}}"
-          {% if owner_references is defined %}
-          ownerReferences: {{owner_references}}
-          {% endif %}
-        spec:
-          selector:
-            app: gordo-grafana-{{project_name}}
-          ports:
-          - port: 3000
-            name: api
-            targetPort: 3000
+    steps:
+      - - name: apply-with-retries
+          template: apply-with-retries
+          arguments:
+            parameters:
+              - name: resource
+                value:  |
+                  ---
+                  apiVersion: v1
+                  kind: Service
+                  metadata:
+                    name: gordo-grafana-{{project_name}}
+                    labels:
+                      app: gordo-grafana-{{project_name}}
+                      app.kubernetes.io/name: grafana
+                      app.kubernetes.io/component: service
+                      app.kubernetes.io/part-of: gordo
+                      app.kubernetes.io/managed-by: gordo
+                      applications.gordo.equinor.com/project-name: "{{project_name}}"
+                      applications.gordo.equinor.com/project-version: "{{project_version}}"
+                    {% if owner_references is defined %}
+                    ownerReferences: {{owner_references}}
+                    {% endif %}
+                  spec:
+                    selector:
+                      app: gordo-grafana-{{project_name}}
+                    ports:
+                    - port: 3000
+                      name: api
+                      targetPort: 3000
 
   - name: gordo-grafana-statefulset
     retryStrategy:
